// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKzXQHefWMPcBUibiEx-WAuODIjMzhDw',
    appId: '1:315854700999:android:a3172a97c2b128990f19e2',
    messagingSenderId: '315854700999',
    projectId: 'route4me-8aae4',
    databaseURL: 'https://route4me-8aae4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'route4me-8aae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjJWZUacvU1vIz_hYkPG8o2s-1oWdNyOE',
    appId: '1:315854700999:ios:fb345ad69106a2770f19e2',
    messagingSenderId: '315854700999',
    projectId: 'route4me-8aae4',
    databaseURL: 'https://route4me-8aae4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'route4me-8aae4.appspot.com',
    iosClientId: '315854700999-2lehoj0f916jqas8i9g490keg6mm5uu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.route4me',
  );
}
